---
- name: PostgreSQL | Register backup file state
  stat:
    path: "{{ backup_tmp_path }}/{{ backup_folder_prefix }}{{ timestamp.stdout }}/postgresql/{{ backup_db.database }}-{{ backup_postgresql_backup_file_name }}"
  register: backup_state

- name: PostgreSQL | Fail when backup was not created
  fail:
    msg: "Backup file was not created"
  when: backup_state.stat.exists == false

- name: PostgreSQL | Fail if the file is too small
  fail:
    msg: "Backup file is too small"
  when: backup_state.stat.size < backup_postgres_size_threshold